# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-05 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='段子内容')),
                ('avator', models.ImageField(default='imgs/default.png', upload_to='avator/')),
            ],
            options={
                'verbose_name': '段子类',
                'verbose_name_plural': '段子类',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('description', models.TextField(verbose_name='概括描述')),
                ('time', models.CharField(max_length=20, verbose_name='时间')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('content', models.TextField(verbose_name='新闻内容')),
            ],
            options={
                'verbose_name': '新闻类',
                'verbose_name_plural': '新闻类',
                'ordering': ['-title'],
            },
        ),
    ]
