# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-08 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='time',
            new_name='time_time',
        ),
        migrations.AddField(
            model_name='news',
            name='from_from',
            field=models.CharField(default='', max_length=200, verbose_name='来源'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=200, verbose_name='作者'),
        ),
    ]
