# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-news_id'], 'verbose_name': '新闻类', 'verbose_name_plural': '新闻类'},
        ),
    ]
