# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190812_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['-vd_id'], 'verbose_name': '视频类', 'verbose_name_plural': '视频类'},
        ),
        migrations.RemoveField(
            model_name='interest',
            name='content',
        ),
        migrations.AddField(
            model_name='interest',
            name='vd_id',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='视频id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='title',
            field=models.TextField(verbose_name='视频标题'),
        ),
    ]
