# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190808_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_id',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='新闻id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='time_time',
            field=models.CharField(max_length=50, verbose_name='时间'),
        ),
    ]
