# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190809_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_url',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='新闻url'),
            preserve_default=False,
        ),
    ]
