# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-16 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190815_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='vd_id',
            field=models.IntegerField(max_length=20, unique=True, verbose_name='视频id'),
        ),
    ]
