# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190816_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='vd_id',
            field=models.IntegerField(unique=True, verbose_name='视频id'),
        ),
    ]
