# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190819_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='all_time',
            field=models.CharField(default='', max_length=10, verbose_name='视频时长'),
            preserve_default=False,
        ),
    ]
