# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='该评论内容')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('isone', models.BooleanField(default=True)),
                ('beuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_beuser', to=settings.AUTH_USER_MODEL, verbose_name='被评论的用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Says',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='说说内容')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('pic', models.CharField(max_length=50, verbose_name='图片')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_user', to=settings.AUTH_USER_MODEL, verbose_name='发说说的用户')),
            ],
            options={
                'verbose_name': '说说',
                'verbose_name_plural': '说说',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='says_comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='says_comments', to='reviews.Says', verbose_name='评论的说说'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to=settings.AUTH_USER_MODEL, verbose_name='该评论的用户'),
        ),
    ]
