# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_comments_isone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='says',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='avator/%Y%m%d/', verbose_name='图片'),
        ),
    ]
