# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(default=1426726364, max_length=11, verbose_name='QQ号'),
            preserve_default=False,
        ),
    ]
