# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_qq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator_sor',
            field=models.ImageField(default='avator/default.png', upload_to='avator/%Y%m%d/', verbose_name='头像'),
        ),
    ]
