# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_findpassword'),
        ('accounts', '0003_auto_20190822_1743'),
    ]

    operations = [
    ]
